nyc_taxi_dbt:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: trino
      method: none
      user: "{{ env_var('TRINO_USER', 'airflow') }}"
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      database: "{{ env_var('TRINO_CATALOG', 'iceberg') }}"
      schema: "{{ env_var('GLUE_DATABASE_STAGING', 'staging') }}"
      threads: 4
      http_scheme: http
